Repository Developer-Groo/Mobble-Server, pull requests merged in 2025-08, with the labels that each got.

#93 Feature/club api
  src/main/java/com/mobble/mobbleserver/domain/article/dto/request/ArticleRequestDto.java
  src/main/java/com/mobble/mobbleserver/domain/article/entity/Article.java
  src/main/java/com/mobble/mobbleserver/domain/article/repository/ArticleQueryRepository.java
  src/main/java/com/mobble/mobbleserver/domain/article/repository/ArticleRepository.java
  src/main/java/com/mobble/mobbleserver/domain/article/repository/ArticleRepositoryImpl.java
  src/main/java/com/mobble/mobbleserver/domain/article/service/ArticleService.java
  src/main/java/com/mobble/mobbleserver/domain/chat/clubChatRoom/entity/ClubChatRoom.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/controller/ClubController.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/dto/request/ClubRequestDto.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/dto/response/ClubResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/entity/Club.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/repository/ClubQueryRepository.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/repository/ClubRepository.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/repository/ClubRepositoryImpl.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/repository/dto/ClubLikeInfoDto.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/service/ClubService.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/validator/ClubValidator.java
  src/main/java/com/mobble/mobbleserver/domain/club/clubAgeGroup/entity/ClubAgeGroup.java
  src/main/java/com/mobble/mobbleserver/domain/club/clubAgeGroup/entity/ClubAgeGroupType.java
  src/main/java/com/mobble/mobbleserver/domain/club/clubAgeGroup/repository/ClubAgeGroupRepository.java
  src/main/java/com/mobble/mobbleserver/domain/club/entity/Club.java
  src/main/java/com/mobble/mobbleserver/domain/club/repository/ClubRepository.java
  src/main/java/com/mobble/mobbleserver/domain/clubAgeGroup/repository/ClubAgeGroupRepository.java
  src/main/java/com/mobble/mobbleserver/domain/clubCategory/entity/ClubCategory.java
  src/main/java/com/mobble/mobbleserver/domain/clubCategory/repository/ClubCategoryRepository.java
  src/main/java/com/mobble/mobbleserver/domain/clubImage/entity/ClubImage.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/entity/ClubMember.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/repository/ClubMemberRepository.java
  src/main/java/com/mobble/mobbleserver/domain/comment/repository/CommentQueryRepository.java
  src/main/java/com/mobble/mobbleserver/domain/comment/repository/CommentRepository.java
  src/main/java/com/mobble/mobbleserver/domain/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/repository/ArticleLikeRepository.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/entity/ClubLike.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/repository/ClubLikeRepository.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/repository/CommentLikeQueryRepository.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/repository/CommentLikeRepository.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/repository/CommentLikeRepositoryImpl.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/club/ClubErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/club/ClubValidationErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/validation/ValidationErrorCodeResolver.java
  src/test/java/com/mobble/mobbleserver/domain/comment/repository/CommentRepositoryImplTest.java
  src/test/java/com/mobble/mobbleserver/domain/comment/service/CommentServiceTest.java
  src/test/java/com/mobble/mobbleserver/support/fixture/article/ArticleTestFixture.java
  src/test/java/com/mobble/mobbleserver/support/fixture/club/ClubTestFixture.java
Labels: feature

#96 Feature/club member api
  src/main/java/com/mobble/mobbleserver/domain/club/club/service/ClubService.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/controller/ClubMemberController.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/dto/request/CreateClubMemberDto.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/dto/request/UpdateClubMemberRoleDto.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/dto/request/UpdateClubMemberStatusDto.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/dto/response/ClubMemberResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/dto/response/ClubMemberUpsertResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/entity/ClubMember.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/entity/JoinStatus.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/repository/ClubMemberRepository.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/service/ClubMemberService.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/validator/ClubMemberValidator.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/club/ClubMemberErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/club/ClubMemberValidationErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/validation/ValidationErrorCodeResolver.java
Labels: feature

#99 Refactor/move leader validation to entity
  src/main/java/com/mobble/mobbleserver/domain/club/club/service/ClubService.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/controller/ClubMemberController.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/entity/ClubMember.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/service/ClubMemberService.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/club/ClubErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/club/ClubMemberErrorCode.java
Labels: refactor

#107 Refactor/article service
  src/main/java/com/mobble/mobbleserver/domain/article/entity/Article.java
  src/main/java/com/mobble/mobbleserver/domain/article/service/ArticleService.java
  src/main/java/com/mobble/mobbleserver/domain/club/club/service/ClubService.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/entity/ClubMember.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/service/ClubMemberService.java
Labels: refactor

#110 Test/article service
  src/test/java/com/mobble/mobbleserver/domain/article/service/ArticleServiceTest.java
Labels: test

#116 Feature/meeting member crud
  src/main/java/com/mobble/mobbleserver/domain/meeting/dto/response/MeetingResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/meeting/entity/Meeting.java
  src/main/java/com/mobble/mobbleserver/domain/meeting/service/MeetingService.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/controller/MeetingMemberController.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/dto/response/MeetingAttendanceResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/dto/response/MeetingMemberListResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/dto/response/MeetingMemberResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/repository/MeetingMemberRepository.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/service/MeetingMemberService.java
Labels: feature

#118 Refactor/login member
  src/main/java/com/mobble/mobbleserver/domain/like/baseLike/controller/LikeController.java
  src/main/java/com/mobble/mobbleserver/domain/meeting/controller/MeetingController.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/controller/MeetingMemberController.java
  src/main/java/com/mobble/mobbleserver/domain/member/controller/MemberController.java
  src/main/java/com/mobble/mobbleserver/domain/member/service/MemberService.java
Labels: refactor

#120 Feature/notification entity
  src/main/java/com/mobble/mobbleserver/domain/comment/service/CommentService.java
  src/main/java/com/mobble/mobbleserver/domain/notification/core/entity/Notification.java
  src/main/java/com/mobble/mobbleserver/domain/notification/core/entity/NotificationTargetType.java
  src/main/java/com/mobble/mobbleserver/domain/notification/core/entity/NotificationType.java
  src/main/java/com/mobble/mobbleserver/domain/notification/core/repository/NotificationRepository.java
  src/main/java/com/mobble/mobbleserver/domain/notification/device/entity/DeviceToken.java
  src/main/java/com/mobble/mobbleserver/domain/notification/device/entity/Platform.java
  src/main/java/com/mobble/mobbleserver/domain/notification/entity/NotificationType.java
  src/main/java/com/mobble/mobbleserver/domain/notification/setting/entity/NotificationSetting.java
  src/main/java/com/mobble/mobbleserver/domain/notification/settingItem/entity/NotificationSettingItem.java
  src/test/java/com/mobble/mobbleserver/domain/comment/service/CommentServiceTest.java
Labels: feature
