Repository Developer-Groo/Mobble-Server, pull requests merged in 2025-09, with the labels that each got.

#132 Refactor/meeting exception
  src/main/java/com/mobble/mobbleserver/domain/meeting/service/MeetingService.java
  src/main/java/com/mobble/mobbleserver/domain/meeting/validator/MeetingValidator.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/service/MeetingMemberService.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/validator/MeetingMemberValidator.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/meeting/MeetingErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/meeting/MeetingMemberErrorCode.java
Labels: refactor

#138 Docs/yml modify
  build.gradle.kts
  src/main/resources/application.yml
Labels: documentation

#151 Test/like service
  src/test/java/com/mobble/mobbleserver/domain/like/articleLike/service/ArticleLikeQueryServiceTest.java
  src/test/java/com/mobble/mobbleserver/domain/like/articleLike/service/ArticleLikeServiceTest.java
  src/test/java/com/mobble/mobbleserver/domain/like/baseLike/service/LikeDispatcherServiceTest.java
  src/test/java/com/mobble/mobbleserver/domain/like/clubLike/service/ClubLikeServiceTest.java
  src/test/java/com/mobble/mobbleserver/domain/like/commentLike/service/CommentLikeServiceTest.java
Labels: test

#162 Test/club member validator test
  src/test/java/com/mobble/mobbleserver/domain/clubMember/service/ClubMemberServiceTest.java
  src/test/java/com/mobble/mobbleserver/domain/clubMember/validator/ClubMemberValidatorTest.java
Labels: test

#178 Update README.md
  README.md
Labels: documentation

#186 Feature/notification
  .github/workflows/ci.yml
  .gitignore
  build.gradle.kts
  src/main/java/com/mobble/mobbleserver/account/auth/service/SignUpDetailsInfoService.java
  src/main/java/com/mobble/mobbleserver/common/baseEntity/CreatedAtEntity.java
  src/main/java/com/mobble/mobbleserver/config/push/FcmClient.java
  src/main/java/com/mobble/mobbleserver/config/push/FcmProperties.java
  src/main/java/com/mobble/mobbleserver/config/push/PushClient.java
  src/main/java/com/mobble/mobbleserver/config/push/PushConfig.java
  src/main/java/com/mobble/mobbleserver/domain/article/dto/response/ArticleSummaryResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/controller/ClubMemberController.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/dto/request/UpdateClubMemberRoleDto.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/service/ClubMemberService.java
  src/main/java/com/mobble/mobbleserver/domain/comment/dto/response/ReplyCommentResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/comment/dto/response/RootCommentResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/comment/repository/CommentQueryRepository.java
  src/main/java/com/mobble/mobbleserver/domain/comment/validator/CommentValidator.java
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/service/ArticleLikeQueryService.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/service/CommentLikeService.java
  src/main/java/com/mobble/mobbleserver/domain/notification/core/controller/NotificationController.java
  src/main/java/com/mobble/mobbleserver/domain/notification/core/dto/NotificationDto.java
  src/main/java/com/mobble/mobbleserver/domain/notification/core/repository/NotificationRepository.java
  src/main/java/com/mobble/mobbleserver/domain/notification/core/service/NotificationService.java
  src/main/java/com/mobble/mobbleserver/domain/notification/core/service/SendNotificationCommand.java
  src/main/java/com/mobble/mobbleserver/domain/notification/device/entity/DeviceToken.java
  src/main/java/com/mobble/mobbleserver/domain/notification/device/repository/DeviceTokenRepository.java
  src/main/java/com/mobble/mobbleserver/domain/notification/device/service/DeviceTokenService.java
  src/main/java/com/mobble/mobbleserver/domain/notification/outbox/entity/PushOutbox.java
  src/main/java/com/mobble/mobbleserver/domain/notification/outbox/entity/Status.java
  src/main/java/com/mobble/mobbleserver/domain/notification/outbox/repository/PushOutboxRepository.java
  src/main/java/com/mobble/mobbleserver/domain/notification/outbox/worker/PushProcessor.java
  src/main/java/com/mobble/mobbleserver/domain/notification/outbox/worker/PushWorker.java
  src/main/java/com/mobble/mobbleserver/domain/notification/setting/entity/NotificationSetting.java
  src/main/java/com/mobble/mobbleserver/domain/notification/setting/entity/NotificationSettingItem.java
  src/main/java/com/mobble/mobbleserver/domain/notification/setting/repository/NotificationSettingRepository.java
  src/main/java/com/mobble/mobbleserver/domain/notification/setting/service/NotificationSettingService.java
  src/main/java/com/mobble/mobbleserver/global/exception/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/mobble/mobbleserver/domain/like/articleLike/service/ArticleLikeQueryServiceTest.java
  src/test/java/com/mobble/mobbleserver/domain/like/baseLike/service/LikeDispatcherServiceTest.java
  src/test/java/com/mobble/mobbleserver/domain/like/clubLike/repository/ClubLikeRepositoryTest.java
  src/test/java/com/mobble/mobbleserver/domain/like/commentLike/entity/CommentLikeTest.java
  src/test/java/com/mobble/mobbleserver/domain/like/commentLike/repository/CommentLikeRepositoryTest.java
  src/test/java/com/mobble/mobbleserver/domain/meeting/validator/MeetingValidatorTest.java
  src/test/java/com/mobble/mobbleserver/domain/meetingMember/entity/MeetingMemberTest.java
  src/test/java/com/mobble/mobbleserver/domain/meetingMember/service/MeetingMemberServiceTest.java
Labels: feature
