Repository Developer-Groo/Mobble-Server, pull requests merged in 2025-07, with the labels that each got.

#12 Feature/meeting entity
  src/main/java/com/mobble/mobbleserver/meeting/entity/Meeting.java
  src/main/java/com/mobble/mobbleserver/meeting/entity/MeetingType.java
  src/main/java/com/mobble/mobbleserver/meeting/repository/MeetingRepository.java
Labels: feature

#23 Feature/club like entity
  src/main/java/com/mobble/mobbleserver/domain/clubLikes/entity/ClubLike.java
  src/main/java/com/mobble/mobbleserver/domain/clubLikes/repository/ClubLikeRepository.java
Labels: feature

#27 Feature/meeting member entity
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/entity/MeetingMember.java
Labels: feature

#35 Feature/comment like api
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/controller/CommentLikeController.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/dto/response/CommentLikeResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/repository/CommentLikeRepository.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/service/CommentLikeService.java
Labels: feature

#37 Bug/article like
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/controller/ArticleLikeController.java
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/service/ArticleLikeService.java
Labels: bug

#38 Feature/club like api
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/controller/ClubLikeController.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/dto/response/ClubLikeResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/entity/ClubLike.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/repository/ClubLikeRepository.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/service/ClubLikeService.java
Labels: feature

#40 Feature/like exception
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/entity/ArticleLike.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/entity/ClubLike.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/entity/CommentLike.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/like/LikeErrorCode.java
Labels: feature

#44 Feature/club category entity
  src/main/java/com/mobble/mobbleserver/domain/clubCategory/entity/ClubCategory.java
  src/main/java/com/mobble/mobbleserver/domain/clubCategory/repository/ClubCategoryRepository.java
Labels: feature

#52 Feature/club member entity
  src/main/java/com/mobble/mobbleserver/domain/clubMember/entity/ClubMember.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/entity/ClubMemberRole.java
  src/main/java/com/mobble/mobbleserver/domain/clubMember/repository/ClubMemberRepository.java
Labels: feature

#55 Feature/club age group entity
  src/main/java/com/mobble/mobbleserver/domain/clubAgeGroup/entity/ClubAgeGroup.java
  src/main/java/com/mobble/mobbleserver/domain/clubAgeGroup/entity/ClubAgeGroupType.java
  src/main/java/com/mobble/mobbleserver/domain/clubAgeGroup/repository/ClubAgeGroupRepository.java
Labels: feature

#57 Refactor/article entity
  src/main/java/com/mobble/mobbleserver/domain/article/entity/Article.java
Labels: feature

#63 Feature/member exception
  src/main/java/com/mobble/mobbleserver/domain/member/controller/MemberController.java
  src/main/java/com/mobble/mobbleserver/domain/member/dto/request/MemberCreateRequestDto.java
  src/main/java/com/mobble/mobbleserver/domain/member/entity/Gender.java
  src/main/java/com/mobble/mobbleserver/domain/member/entity/Member.java
  src/main/java/com/mobble/mobbleserver/domain/member/repository/MemberRepository.java
  src/main/java/com/mobble/mobbleserver/domain/member/service/MemberService.java
  src/main/java/com/mobble/mobbleserver/domain/member/validator/MemberValidator.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/member/MemberErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/member/MemberValidationErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/validation/ValidationErrorCodeResolver.java
Labels: feature

#67 Feature/comment test
  src/main/java/com/mobble/mobbleserver/domain/comment/dto/response/CommentResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/comment/dto/response/ReplyCommentDto.java
  src/main/java/com/mobble/mobbleserver/domain/comment/entity/Comment.java
  src/main/java/com/mobble/mobbleserver/domain/comment/service/CommentService.java
  src/main/java/com/mobble/mobbleserver/domain/comment/validator/CommentValidator.java
  src/test/java/com/mobble/mobbleserver/domain/comment/entity/CommentTest.java
  src/test/java/com/mobble/mobbleserver/domain/comment/repository/CommentRepositoryImplTest.java
  src/test/java/com/mobble/mobbleserver/domain/comment/service/CommentServiceTest.java
  src/test/java/com/mobble/mobbleserver/domain/comment/validator/CommentValidatorTest.java
  src/test/java/com/mobble/mobbleserver/support/fixture/article/ArticleTestFixture.java
  src/test/java/com/mobble/mobbleserver/support/fixture/club/ClubTestFixture.java
  src/test/java/com/mobble/mobbleserver/support/fixture/comment/CommentTestFixture.java
  src/test/java/com/mobble/mobbleserver/support/fixture/member/MemberTestFixture.java
Labels: test

#72 Refactor/like refactor method
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/controller/ArticleLikeController.java
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/dto/response/ArticleLikeMemberListResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/dto/response/ArticleToggleLikeResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/entity/ArticleLike.java
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/service/ArticleLikeService.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/dto/response/ClubLikeResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/entity/ClubLike.java
  src/main/java/com/mobble/mobbleserver/domain/like/clubLike/service/ClubLikeService.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/dto/response/CommentLikeResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/entity/CommentLike.java
  src/main/java/com/mobble/mobbleserver/domain/like/commentLike/service/CommentLikeService.java
Labels: refactor

#80 Refactor/comment service
  src/main/java/com/mobble/mobbleserver/config/QueryDslConfig.java
  src/main/java/com/mobble/mobbleserver/domain/article/entity/Article.java
  src/main/java/com/mobble/mobbleserver/domain/article/entity/ArticleType.java
  src/main/java/com/mobble/mobbleserver/domain/article/repository/ArticleRepository.java
  src/main/java/com/mobble/mobbleserver/domain/clubAgeGroup/entity/ClubAgeGroupType.java
  src/main/java/com/mobble/mobbleserver/domain/clubCategory/entity/ClubCategory.java
  src/main/java/com/mobble/mobbleserver/domain/comment/service/CommentService.java
  src/main/java/com/mobble/mobbleserver/domain/like/articleLike/dto/response/ArticleLikeMemberListResponseDto.java
  src/main/java/com/mobble/mobbleserver/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/mobble/mobbleserver/domain/meetingMember/repository/MeetingMemberRepository.java
  src/main/java/com/mobble/mobbleserver/domain/member/Scheduler/MemberDeleteScheduler.java
  src/main/java/com/mobble/mobbleserver/domain/member/controller/MemberController.java
  src/main/java/com/mobble/mobbleserver/domain/member/dto/request/MemberCreateRequestDto.java
  src/main/java/com/mobble/mobbleserver/domain/member/dto/response/MemberResponseDto.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/global/GlobalErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/errorCode/like/LikeErrorCode.java
  src/main/java/com/mobble/mobbleserver/global/exception/handler/GlobalExceptionHandler.java
  src/test/java/com/mobble/mobbleserver/domain/comment/entity/CommentTest.java
  src/test/java/com/mobble/mobbleserver/domain/comment/repository/CommentRepositoryImplTest.java
  src/test/java/com/mobble/mobbleserver/domain/comment/service/CommentServiceTest.java
  src/test/java/com/mobble/mobbleserver/domain/comment/validator/CommentValidatorTest.java
  src/test/java/com/mobble/mobbleserver/support/fixture/member/MemberTestFixture.java
Labels: refactor

#84 Feature/chat entity
  src/main/java/com/mobble/mobbleserver/domain/chat/chatMessage/entity/ChatMessage.java
  src/main/java/com/mobble/mobbleserver/domain/chat/chatMessage/entity/MessageType.java
  src/main/java/com/mobble/mobbleserver/domain/chat/chatMessage/repository/ChatMessageRepository.java
  src/main/java/com/mobble/mobbleserver/domain/chat/chatMessageMention/entity/ChatMessageMention.java
  src/main/java/com/mobble/mobbleserver/domain/chat/chatMessageMention/repository/ChatMessageMentionRepository.java
  src/main/java/com/mobble/mobbleserver/domain/chat/chatRoom/entity/ChatRoom.java
  src/main/java/com/mobble/mobbleserver/domain/chat/chatRoom/entity/ChatRoomType.java
  src/main/java/com/mobble/mobbleserver/domain/chat/chatRoom/repository/ChatRoomRepository.java
  src/main/java/com/mobble/mobbleserver/domain/chat/chatRoomParticipant/entity/ChatRoomParticipant.java
  src/main/java/com/mobble/mobbleserver/domain/chat/chatRoomParticipant/repository/ChatRoomParticipantRepository.java
  src/main/java/com/mobble/mobbleserver/domain/chat/clubChatRoom/entity/ClubChatRoom.java
  src/main/java/com/mobble/mobbleserver/domain/chat/clubChatRoom/repository/ClubChatRoomRepository.java
  src/main/java/com/mobble/mobbleserver/domain/chat/directChatRoom/entity/DirectChatRoom.java
  src/main/java/com/mobble/mobbleserver/domain/chat/directChatRoom/repository/DirectChatRoomRepository.java
Labels: feature

#87 Feature/notification entity
  src/main/java/com/mobble/mobbleserver/domain/notification/entity/Notification.java
  src/main/java/com/mobble/mobbleserver/domain/notification/entity/NotificationType.java
  src/main/java/com/mobble/mobbleserver/domain/notification/repository/NotificationRepository.java
Labels: feature

#90 Feature/util timestamp
  src/main/java/com/mobble/mobbleserver/global/exception/handler/dto/ErrorResponseDto.java
  src/main/java/com/mobble/mobbleserver/util/DateTimeUtils.java
Labels: refactor
